-- Migration: 0001_student_changes
-- Description: Make group_id nullable and student_id autoincrementing

-- 1. Make group_id nullable
ALTER TABLE student ALTER COLUMN group_id DROP NOT NULL;

-- 2. Setup student_id as autoincrementing (IDENTITY)
-- First, if there are existing records, we should ensure the sequence starts after the max value.
-- If the column is already an Integer, we add the GENERATED identity property.
ALTER TABLE student ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Optional: If you already have data, you might need to sync the sequence:
-- SELECT setval(pg_get_serial_sequence('student', 'student_id'), coalesce(max(student_id), 0) + 1, false) FROM student;
